info:
  component: Zuul Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  routes:
  #productcomposite - > nombre del MS que se define en el application de MS
    bdmbiometricosorquest:
      path: /WS_BancaDigital/**
      serviceId: bdmbiometricosorquest
#      stripPrefix: false
    bdmbiometricosdummy:
       path: /WS_BiometricosDummy/**
       serviceId: bdmbiometricosdummy

#Puerto por el que levanta ZUUL
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.51.58.240:8761/eureka/
  instance:
    hostname: 10.51.58.240
    nonSecurePort: 8099
